openapi: "3.0.3"
info:
  title: "br_com_redosul_server API"
  description: "br_com_redosul_server API"
  version: "1.0.0"
servers:
- url: "https://br_com_redosul_server"
paths:
  /:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Hello World!"
  /products:
    get:
      description: ""
      parameters:
      - name: "categoryId"
        in: "query"
        required: false
        schema:
          type: "object"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Iterable"
    post:
      description: ""
      parameters:
      - name: "categoryId"
        in: "query"
        required: false
        schema:
          type: "object"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Pair"
  /products/{id}:
    delete:
      description: ""
      parameters:
      - name: "categoryId"
        in: "query"
        required: false
        schema:
          type: "object"
      - name: "parent"
        in: "query"
        required: false
        schema:
          type: "object"
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "object"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Pair"
    get:
      description: ""
      parameters:
      - name: "categoryId"
        in: "query"
        required: false
        schema:
          type: "object"
      - name: "parent"
        in: "query"
        required: false
        schema:
          type: "object"
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "object"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Pair"
    post:
      description: ""
      parameters:
      - name: "categoryId"
        in: "query"
        required: false
        schema:
          type: "object"
      - name: "parent"
        in: "query"
        required: false
        schema:
          type: "object"
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "object"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Product"
  /categories:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/CategoryTreeDto"
    post:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CategoryDto"
  /categories/{id}:
    delete:
      description: ""
      parameters:
      - name: "parent"
        in: "query"
        required: true
        schema:
          type: "object"
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "object"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CategoryDto"
    get:
      description: ""
      parameters:
      - name: "parent"
        in: "query"
        required: true
        schema:
          type: "object"
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "object"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CategoryDto"
    post:
      description: ""
      parameters:
      - name: "parent"
        in: "query"
        required: true
        schema:
          type: "object"
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "object"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CategoryDto"
components:
  schemas:
    Iterable:
      type: "object"
      properties: {}
    Pair:
      type: "object"
      properties: {}
    Product:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        createdAt:
          type: "string"
          format: "date-time"
        updatedAt:
          type: "string"
          format: "date-time"
        categoryId:
          type: "string"
          format: "uuid"
        name:
          type: "string"
        slug:
          type: "string"
        description:
          type: "string"
    CategoryTreeDto:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        name:
          type: "string"
        slug:
          type: "string"
        description:
          type: "string"
        children:
          type: "array"
          items:
            $ref: "#/components/schemas/CategoryTreeDto"
    CategoryDto:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        parentId:
          type: "string"
          format: "uuid"
        name:
          type: "string"
        slug:
          type: "string"
        description:
          type: "string"
        createdAt:
          type: "string"
          format: "date-time"
        updatedAt:
          type: "string"
          format: "date-time"