GET http://localhost:8080/products
Accept: application/json

###
POST http://localhost:8080/products
Content-Type: application/json

{
  "categoryId": "4dedba12-e47b-4e54-bbd9-95790f3beb3b",
  "name": "Product 8",
  "variants": [
    {
      "type": "RGB",
      "red": 255,
      "green": 0,
      "blue": 0
    },
    {
      "type": "RGB",
      "red": 0,
      "green": 255,
      "blue": 0
    },
    {
      "type": "RGB",
      "red": 0,
      "green": 0,
      "blue": 255
    }
  ]
}

###
GET http://localhost:8080/products/efe3bcb3-999b-499d-9ef0-0ab463108312
Accept: application/json

###
POST http://localhost:8080/products/efe3bcb3-999b-499d-9ef0-0ab463108312
Content-Type: application/json

{
  "id": "efe3bcb3-999b-499d-9ef0-0ab463108312",
  "categoryId": "4dedba12-e47b-4e54-bbd9-95790f3beb3b",
  "name": "Product 8",
  "slug": "product-8",
  "description": "",
  "variants": [
    {
      "type": "RGB",
      "name": "",
      "red": 255,
      "green": 255,
      "blue": 255
    },
    {
      "type": "RGB",
      "id": "004ce0e5-f7b9-46d8-bf33-bc346a87b2b6",
      "name": "",
      "red": 0,
      "green": 255,
      "blue": 255
    }
  ]
}

###
DELETE http://localhost:8080/products/e5d9763f-db6b-4037-9090-01512d651a20
Content-Type: application/json

###