GET http://localhost:8080/products
Accept: application/json

###
POST http://localhost:8080/products
Content-Type: application/json

{
  "categoryId": 1,
  "name": "Product grand parent"
}

###
GET http://localhost:8080/products/1
Accept: application/json

###
POST http://localhost:8080/products/1
Content-Type: application/json

{
  "categoryId": 1,
  "name": "Other Product"
}

###
DELETE http://localhost:8080/products/1
Content-Type: application/json

###