GET http://localhost:8080/products
Accept: application/json

###
POST http://localhost:8080/products
Content-Type: application/json

{
  "categoryId": "4dedba12-e47b-4e54-bbd9-95790f3beb3b",
  "name": "Product 9",
  "variants": [
    {
      "type": "RGB",
      "red": 255,
      "green": 0,
      "blue": 0
    },
    {
      "type": "RGB",
      "red": 0,
      "green": 255,
      "blue": 0
    },
    {
      "type": "RGB",
      "red": 0,
      "green": 0,
      "blue": 255
    }
  ]
}

###
GET http://localhost:8080/products/1fb142f6-74e1-47fd-a4ef-afbf6d55ce12
Accept: application/json

###
POST http://localhost:8080/products/1fb142f6-74e1-47fd-a4ef-afbf6d55ce12
Content-Type: application/json

{
  "categoryId": "32b6498a-4ba8-4789-b41f-9027a1e814c5",
  "name": "Product 8 outro",
  "variants": [
    {
      "type": "RGB",
      "name": "",
      "red": 255,
      "green": 255,
      "blue": 255
    },
    {
      "type": "RGB",
      "id": "38dad0c4-8182-4595-8dfb-3fe41bcd0417",
      "name": "",
      "red": 0,
      "green": 255,
      "blue": 255
    }
  ]
}

###
DELETE http://localhost:8080/products/1fb142f6-74e1-47fd-a4ef-afbf6d55ce12
Content-Type: application/json

###