GET http://localhost:8080/categories
Accept: application/json

###
POST http://localhost:8080/categories
Content-Type: application/json

{
  "name": "Category"
}

###
GET http://localhost:8080/categories/32b6498a-4ba8-4789-b41f-9027a1e814c5
Accept: application/json

###
POST http://localhost:8080/categories/6ea5f793-e80c-4339-878c-ab0031ccedec
Content-Type: application/json

{
  "name": "New Category"
}

###
DELETE http://localhost:8080/categories/6ea5f793-e80c-4339-878c-ab0031ccedec
Content-Type: application/json

###